/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Addresses controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { AddressCreateDTO, AddressResponseDTOListResponseDTO, AddressResponseDTOResponseDTO, AddressUpdateDTO, ObjectResponseDTO, RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";

@Injectable({ providedIn: "root" })
export class AddressesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    addressesAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponseDTOListResponseDTO>;
    addressesAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponseDTOListResponseDTO>>;
    addressesAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponseDTOListResponseDTO>>;
    addressesAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    addressesIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponseDTOResponseDTO>;
    addressesIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponseDTOResponseDTO>>;
    addressesIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponseDTOResponseDTO>>;
    addressesIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    addressesUserUserIdGet(userId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponseDTOListResponseDTO>;
    addressesUserUserIdGet(userId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponseDTOListResponseDTO>>;
    addressesUserUserIdGet(userId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponseDTOListResponseDTO>>;
    addressesUserUserIdGet(userId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/user/${userId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    addressesCreatePost(addressCreateDTO?: AddressCreateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponseDTOResponseDTO>;
    addressesCreatePost(addressCreateDTO?: AddressCreateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponseDTOResponseDTO>>;
    addressesCreatePost(addressCreateDTO?: AddressCreateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponseDTOResponseDTO>>;
    addressesCreatePost(addressCreateDTO?: AddressCreateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, addressCreateDTO, requestOptions);
    }

    addressesUpdateIdPut(id: string, addressUpdateDTO?: AddressUpdateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressResponseDTOResponseDTO>;
    addressesUpdateIdPut(id: string, addressUpdateDTO?: AddressUpdateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressResponseDTOResponseDTO>>;
    addressesUpdateIdPut(id: string, addressUpdateDTO?: AddressUpdateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressResponseDTOResponseDTO>>;
    addressesUpdateIdPut(id: string, addressUpdateDTO?: AddressUpdateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, addressUpdateDTO, requestOptions);
    }

    addressesDeleteIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponseDTO>;
    addressesDeleteIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponseDTO>>;
    addressesDeleteIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponseDTO>>;
    addressesDeleteIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
