/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for CategoryCursus controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { CategoryCursusCreateDTO, CategoryCursusResponseDTOListResponseDTO, CategoryCursusResponseDTOResponseDTO, CategoryCursusUpdateDTO, ObjectResponseDTO, RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";

@Injectable({ providedIn: "root" })
export class CategoryCursusService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    categorycursusAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryCursusResponseDTOListResponseDTO>;
    categorycursusAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryCursusResponseDTOListResponseDTO>>;
    categorycursusAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryCursusResponseDTOListResponseDTO>>;
    categorycursusAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categorycursus/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    categorycursusIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryCursusResponseDTOResponseDTO>;
    categorycursusIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryCursusResponseDTOResponseDTO>>;
    categorycursusIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryCursusResponseDTOResponseDTO>>;
    categorycursusIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categorycursus/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    categorycursusCreatePost(categoryCursusCreateDTO?: CategoryCursusCreateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryCursusResponseDTOResponseDTO>;
    categorycursusCreatePost(categoryCursusCreateDTO?: CategoryCursusCreateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryCursusResponseDTOResponseDTO>>;
    categorycursusCreatePost(categoryCursusCreateDTO?: CategoryCursusCreateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryCursusResponseDTOResponseDTO>>;
    categorycursusCreatePost(categoryCursusCreateDTO?: CategoryCursusCreateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categorycursus/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, categoryCursusCreateDTO, requestOptions);
    }

    categorycursusUpdateIdPut(id: string, categoryCursusUpdateDTO?: CategoryCursusUpdateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryCursusResponseDTOResponseDTO>;
    categorycursusUpdateIdPut(id: string, categoryCursusUpdateDTO?: CategoryCursusUpdateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryCursusResponseDTOResponseDTO>>;
    categorycursusUpdateIdPut(id: string, categoryCursusUpdateDTO?: CategoryCursusUpdateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryCursusResponseDTOResponseDTO>>;
    categorycursusUpdateIdPut(id: string, categoryCursusUpdateDTO?: CategoryCursusUpdateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categorycursus/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, categoryCursusUpdateDTO, requestOptions);
    }

    categorycursusDeleteIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponseDTO>;
    categorycursusDeleteIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponseDTO>>;
    categorycursusDeleteIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponseDTO>>;
    categorycursusDeleteIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categorycursus/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
