/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Experiences controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { ExperienceCreateDTO, ExperienceResponseDTOListResponseDTO, ExperienceResponseDTOResponseDTO, ExperienceUpdateDTO, ObjectResponseDTO, RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";

@Injectable({ providedIn: "root" })
export class ExperiencesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    experiencesAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<ExperienceResponseDTOListResponseDTO>;
    experiencesAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ExperienceResponseDTOListResponseDTO>>;
    experiencesAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ExperienceResponseDTOListResponseDTO>>;
    experiencesAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/experiences/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    experiencesIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ExperienceResponseDTOResponseDTO>;
    experiencesIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ExperienceResponseDTOResponseDTO>>;
    experiencesIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ExperienceResponseDTOResponseDTO>>;
    experiencesIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/experiences/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    experiencesUserUserIdGet(userId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ExperienceResponseDTOListResponseDTO>;
    experiencesUserUserIdGet(userId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ExperienceResponseDTOListResponseDTO>>;
    experiencesUserUserIdGet(userId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ExperienceResponseDTOListResponseDTO>>;
    experiencesUserUserIdGet(userId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/experiences/user/${userId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    experiencesCreatePost(experienceCreateDTO?: ExperienceCreateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<ExperienceResponseDTOResponseDTO>;
    experiencesCreatePost(experienceCreateDTO?: ExperienceCreateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ExperienceResponseDTOResponseDTO>>;
    experiencesCreatePost(experienceCreateDTO?: ExperienceCreateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ExperienceResponseDTOResponseDTO>>;
    experiencesCreatePost(experienceCreateDTO?: ExperienceCreateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/experiences/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, experienceCreateDTO, requestOptions);
    }

    experiencesUpdateIdPut(id: string, experienceUpdateDTO?: ExperienceUpdateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<ExperienceResponseDTOResponseDTO>;
    experiencesUpdateIdPut(id: string, experienceUpdateDTO?: ExperienceUpdateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ExperienceResponseDTOResponseDTO>>;
    experiencesUpdateIdPut(id: string, experienceUpdateDTO?: ExperienceUpdateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ExperienceResponseDTOResponseDTO>>;
    experiencesUpdateIdPut(id: string, experienceUpdateDTO?: ExperienceUpdateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/experiences/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, experienceUpdateDTO, requestOptions);
    }

    experiencesDeleteIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponseDTO>;
    experiencesDeleteIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponseDTO>>;
    experiencesDeleteIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponseDTO>>;
    experiencesDeleteIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/experiences/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
