/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Favorites controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BooleanResponseDTO, FavoriteCreateDTO, FavoriteDynamicFilters, FavoriteResponseDTOListResponseDTO, FavoriteResponseDTOResponseDTO, FavoriteUpdateDTO, ObjectResponseDTO, RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";

@Injectable({ providedIn: "root" })
export class FavoritesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    favoritesMyFavoritesPost(favoriteDynamicFilters?: FavoriteDynamicFilters, observe?: 'body', options?: RequestOptions<'json'>): Observable<FavoriteResponseDTOListResponseDTO>;
    favoritesMyFavoritesPost(favoriteDynamicFilters?: FavoriteDynamicFilters, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FavoriteResponseDTOListResponseDTO>>;
    favoritesMyFavoritesPost(favoriteDynamicFilters?: FavoriteDynamicFilters, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FavoriteResponseDTOListResponseDTO>>;
    favoritesMyFavoritesPost(favoriteDynamicFilters?: FavoriteDynamicFilters, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/my-favorites`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, favoriteDynamicFilters, requestOptions);
    }

    favoritesMyFansGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<FavoriteResponseDTOListResponseDTO>;
    favoritesMyFansGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FavoriteResponseDTOListResponseDTO>>;
    favoritesMyFansGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FavoriteResponseDTOListResponseDTO>>;
    favoritesMyFansGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/my-fans`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    favoritesTeacherTeacherIdFansGet(teacherId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<FavoriteResponseDTOListResponseDTO>;
    favoritesTeacherTeacherIdFansGet(teacherId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FavoriteResponseDTOListResponseDTO>>;
    favoritesTeacherTeacherIdFansGet(teacherId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FavoriteResponseDTOListResponseDTO>>;
    favoritesTeacherTeacherIdFansGet(teacherId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/teacher/${teacherId}/fans`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    favoritesIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<FavoriteResponseDTOResponseDTO>;
    favoritesIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FavoriteResponseDTOResponseDTO>>;
    favoritesIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FavoriteResponseDTOResponseDTO>>;
    favoritesIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    favoritesAddPost(favoriteCreateDTO?: FavoriteCreateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<FavoriteResponseDTOResponseDTO>;
    favoritesAddPost(favoriteCreateDTO?: FavoriteCreateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FavoriteResponseDTOResponseDTO>>;
    favoritesAddPost(favoriteCreateDTO?: FavoriteCreateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FavoriteResponseDTOResponseDTO>>;
    favoritesAddPost(favoriteCreateDTO?: FavoriteCreateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/add`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, favoriteCreateDTO, requestOptions);
    }

    favoritesUpdateIdPut(id: string, favoriteUpdateDTO?: FavoriteUpdateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<FavoriteResponseDTOResponseDTO>;
    favoritesUpdateIdPut(id: string, favoriteUpdateDTO?: FavoriteUpdateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FavoriteResponseDTOResponseDTO>>;
    favoritesUpdateIdPut(id: string, favoriteUpdateDTO?: FavoriteUpdateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FavoriteResponseDTOResponseDTO>>;
    favoritesUpdateIdPut(id: string, favoriteUpdateDTO?: FavoriteUpdateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, favoriteUpdateDTO, requestOptions);
    }

    favoritesRemoveIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponseDTO>;
    favoritesRemoveIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponseDTO>>;
    favoritesRemoveIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponseDTO>>;
    favoritesRemoveIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/remove/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    favoritesIsFavoriteTeacherIdGet(teacherId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<BooleanResponseDTO>;
    favoritesIsFavoriteTeacherIdGet(teacherId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<BooleanResponseDTO>>;
    favoritesIsFavoriteTeacherIdGet(teacherId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<BooleanResponseDTO>>;
    favoritesIsFavoriteTeacherIdGet(teacherId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/is-favorite/${teacherId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
