/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Formations controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BooleanResponseDTO, FormationCreateDTO, FormationResponseDTOListResponseDTO, FormationResponseDTOResponseDTO, FormationUpdateDTO, RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";

@Injectable({ providedIn: "root" })
export class FormationsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    formationsAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<FormationResponseDTOListResponseDTO>;
    formationsAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormationResponseDTOListResponseDTO>>;
    formationsAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormationResponseDTOListResponseDTO>>;
    formationsAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    formationsIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<FormationResponseDTOResponseDTO>;
    formationsIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormationResponseDTOResponseDTO>>;
    formationsIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormationResponseDTOResponseDTO>>;
    formationsIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    formationsUserUserIdGet(userId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<FormationResponseDTOListResponseDTO>;
    formationsUserUserIdGet(userId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormationResponseDTOListResponseDTO>>;
    formationsUserUserIdGet(userId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormationResponseDTOListResponseDTO>>;
    formationsUserUserIdGet(userId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/user/${userId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    formationsCreatePost(formationCreateDTO?: FormationCreateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<FormationResponseDTOResponseDTO>;
    formationsCreatePost(formationCreateDTO?: FormationCreateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormationResponseDTOResponseDTO>>;
    formationsCreatePost(formationCreateDTO?: FormationCreateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormationResponseDTOResponseDTO>>;
    formationsCreatePost(formationCreateDTO?: FormationCreateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formationCreateDTO, requestOptions);
    }

    formationsUpdateIdPut(id: string, formationUpdateDTO?: FormationUpdateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<FormationResponseDTOResponseDTO>;
    formationsUpdateIdPut(id: string, formationUpdateDTO?: FormationUpdateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormationResponseDTOResponseDTO>>;
    formationsUpdateIdPut(id: string, formationUpdateDTO?: FormationUpdateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormationResponseDTOResponseDTO>>;
    formationsUpdateIdPut(id: string, formationUpdateDTO?: FormationUpdateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, formationUpdateDTO, requestOptions);
    }

    formationsDeleteIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<BooleanResponseDTO>;
    formationsDeleteIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<BooleanResponseDTO>>;
    formationsDeleteIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<BooleanResponseDTO>>;
    formationsDeleteIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
