/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for LevelCursus controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { LevelCursusCreateDTO, LevelCursusResponseDTOListResponseDTO, LevelCursusResponseDTOResponseDTO, LevelCursusUpdateDTO, ObjectResponseDTO, RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";

@Injectable({ providedIn: "root" })
export class LevelCursusService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    levelcursusAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelCursusResponseDTOListResponseDTO>;
    levelcursusAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelCursusResponseDTOListResponseDTO>>;
    levelcursusAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelCursusResponseDTOListResponseDTO>>;
    levelcursusAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/levelcursus/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    levelcursusIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelCursusResponseDTOResponseDTO>;
    levelcursusIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelCursusResponseDTOResponseDTO>>;
    levelcursusIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelCursusResponseDTOResponseDTO>>;
    levelcursusIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/levelcursus/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    levelcursusCreatePost(levelCursusCreateDTO?: LevelCursusCreateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelCursusResponseDTOResponseDTO>;
    levelcursusCreatePost(levelCursusCreateDTO?: LevelCursusCreateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelCursusResponseDTOResponseDTO>>;
    levelcursusCreatePost(levelCursusCreateDTO?: LevelCursusCreateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelCursusResponseDTOResponseDTO>>;
    levelcursusCreatePost(levelCursusCreateDTO?: LevelCursusCreateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/levelcursus/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, levelCursusCreateDTO, requestOptions);
    }

    levelcursusUpdateIdPut(id: string, levelCursusUpdateDTO?: LevelCursusUpdateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelCursusResponseDTOResponseDTO>;
    levelcursusUpdateIdPut(id: string, levelCursusUpdateDTO?: LevelCursusUpdateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelCursusResponseDTOResponseDTO>>;
    levelcursusUpdateIdPut(id: string, levelCursusUpdateDTO?: LevelCursusUpdateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelCursusResponseDTOResponseDTO>>;
    levelcursusUpdateIdPut(id: string, levelCursusUpdateDTO?: LevelCursusUpdateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/levelcursus/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, levelCursusUpdateDTO, requestOptions);
    }

    levelcursusDeleteIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponseDTO>;
    levelcursusDeleteIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponseDTO>>;
    levelcursusDeleteIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponseDTO>>;
    levelcursusDeleteIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/levelcursus/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
