/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Slots controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BookingCreateDTO, BookingUpdateDTO, ObjectResponseDTO, RequestOptions, SlotCreateDTO, SlotDynamicFilters, SlotResponseDTOListResponseDTO, SlotResponseDTOResponseDTO, SlotUpdateDTO } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";

@Injectable({ providedIn: "root" })
export class SlotsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    slotsAllPost(slotDynamicFilters?: SlotDynamicFilters, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotResponseDTOListResponseDTO>;
    slotsAllPost(slotDynamicFilters?: SlotDynamicFilters, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotResponseDTOListResponseDTO>>;
    slotsAllPost(slotDynamicFilters?: SlotDynamicFilters, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotResponseDTOListResponseDTO>>;
    slotsAllPost(slotDynamicFilters?: SlotDynamicFilters, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, slotDynamicFilters, requestOptions);
    }

    slotsIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotResponseDTOResponseDTO>;
    slotsIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotResponseDTOResponseDTO>>;
    slotsIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotResponseDTOResponseDTO>>;
    slotsIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    slotsTeacherTeacherIdGet(teacherId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotResponseDTOListResponseDTO>;
    slotsTeacherTeacherIdGet(teacherId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotResponseDTOListResponseDTO>>;
    slotsTeacherTeacherIdGet(teacherId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotResponseDTOListResponseDTO>>;
    slotsTeacherTeacherIdGet(teacherId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/${teacherId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    slotsStudentGet(dateFrom?: Date, dateTo?: Date, teacherId?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotResponseDTOListResponseDTO>;
    slotsStudentGet(dateFrom?: Date, dateTo?: Date, teacherId?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotResponseDTOListResponseDTO>>;
    slotsStudentGet(dateFrom?: Date, dateTo?: Date, teacherId?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotResponseDTOListResponseDTO>>;
    slotsStudentGet(dateFrom?: Date, dateTo?: Date, teacherId?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/student`;

        let params = new HttpParams();
        if (dateFrom != null) {
            params = HttpParamsBuilder.addToHttpParams(params, dateFrom, 'dateFrom');
        }
        if (dateTo != null) {
            params = HttpParamsBuilder.addToHttpParams(params, dateTo, 'dateTo');
        }
        if (teacherId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, teacherId, 'teacherId');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    slotsAvailableGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotResponseDTOListResponseDTO>;
    slotsAvailableGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotResponseDTOListResponseDTO>>;
    slotsAvailableGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotResponseDTOListResponseDTO>>;
    slotsAvailableGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/available`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    slotsCreatePost(slotCreateDTO?: SlotCreateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotResponseDTOResponseDTO>;
    slotsCreatePost(slotCreateDTO?: SlotCreateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotResponseDTOResponseDTO>>;
    slotsCreatePost(slotCreateDTO?: SlotCreateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotResponseDTOResponseDTO>>;
    slotsCreatePost(slotCreateDTO?: SlotCreateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, slotCreateDTO, requestOptions);
    }

    slotsUpdateIdPut(id: string, slotUpdateDTO?: SlotUpdateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotResponseDTOResponseDTO>;
    slotsUpdateIdPut(id: string, slotUpdateDTO?: SlotUpdateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotResponseDTOResponseDTO>>;
    slotsUpdateIdPut(id: string, slotUpdateDTO?: SlotUpdateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotResponseDTOResponseDTO>>;
    slotsUpdateIdPut(id: string, slotUpdateDTO?: SlotUpdateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, slotUpdateDTO, requestOptions);
    }

    slotsUpdateBookingPut(bookingUpdateDTO?: BookingUpdateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotResponseDTOResponseDTO>;
    slotsUpdateBookingPut(bookingUpdateDTO?: BookingUpdateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotResponseDTOResponseDTO>>;
    slotsUpdateBookingPut(bookingUpdateDTO?: BookingUpdateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotResponseDTOResponseDTO>>;
    slotsUpdateBookingPut(bookingUpdateDTO?: BookingUpdateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/update-booking`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, bookingUpdateDTO, requestOptions);
    }

    slotsConfirmBookingIdPut(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotResponseDTOResponseDTO>;
    slotsConfirmBookingIdPut(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotResponseDTOResponseDTO>>;
    slotsConfirmBookingIdPut(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotResponseDTOResponseDTO>>;
    slotsConfirmBookingIdPut(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/confirm-booking/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, null, requestOptions);
    }

    slotsDeleteIdDelete(id: string, forceDelete?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponseDTO>;
    slotsDeleteIdDelete(id: string, forceDelete?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponseDTO>>;
    slotsDeleteIdDelete(id: string, forceDelete?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponseDTO>>;
    slotsDeleteIdDelete(id: string, forceDelete?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/delete/${id}`;

        let params = new HttpParams();
        if (forceDelete != null) {
            params = HttpParamsBuilder.addToHttpParams(params, forceDelete, 'forceDelete');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    slotsBookPost(bookingCreateDTO?: BookingCreateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponseDTO>;
    slotsBookPost(bookingCreateDTO?: BookingCreateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponseDTO>>;
    slotsBookPost(bookingCreateDTO?: BookingCreateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponseDTO>>;
    slotsBookPost(bookingCreateDTO?: BookingCreateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/book`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, bookingCreateDTO, requestOptions);
    }

    slotsUnbookIdPost(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponseDTO>;
    slotsUnbookIdPost(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponseDTO>>;
    slotsUnbookIdPost(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponseDTO>>;
    slotsUnbookIdPost(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/unbook/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    slotsBookingsPost(slotDynamicFilters?: SlotDynamicFilters, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotResponseDTOListResponseDTO>;
    slotsBookingsPost(slotDynamicFilters?: SlotDynamicFilters, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotResponseDTOListResponseDTO>>;
    slotsBookingsPost(slotDynamicFilters?: SlotDynamicFilters, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotResponseDTOListResponseDTO>>;
    slotsBookingsPost(slotDynamicFilters?: SlotDynamicFilters, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/bookings`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, slotDynamicFilters, requestOptions);
    }
}
