/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for StatusAccount controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { ObjectResponseDTO, RequestOptions, StatusAccountCreateDTO, StatusAccountDynamicFilters, StatusAccountResponseDTOListResponseDTO, StatusAccountResponseDTOResponseDTO, StatusAccountUpdateDTO } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";

@Injectable({ providedIn: "root" })
export class StatusAccountService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    statusaccountAllPost(statusAccountDynamicFilters?: StatusAccountDynamicFilters, observe?: 'body', options?: RequestOptions<'json'>): Observable<StatusAccountResponseDTOListResponseDTO>;
    statusaccountAllPost(statusAccountDynamicFilters?: StatusAccountDynamicFilters, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<StatusAccountResponseDTOListResponseDTO>>;
    statusaccountAllPost(statusAccountDynamicFilters?: StatusAccountDynamicFilters, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<StatusAccountResponseDTOListResponseDTO>>;
    statusaccountAllPost(statusAccountDynamicFilters?: StatusAccountDynamicFilters, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/statusaccount/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, statusAccountDynamicFilters, requestOptions);
    }

    statusaccountIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<StatusAccountResponseDTOResponseDTO>;
    statusaccountIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<StatusAccountResponseDTOResponseDTO>>;
    statusaccountIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<StatusAccountResponseDTOResponseDTO>>;
    statusaccountIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/statusaccount/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    statusaccountCreatePost(statusAccountCreateDTO?: StatusAccountCreateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<StatusAccountResponseDTOResponseDTO>;
    statusaccountCreatePost(statusAccountCreateDTO?: StatusAccountCreateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<StatusAccountResponseDTOResponseDTO>>;
    statusaccountCreatePost(statusAccountCreateDTO?: StatusAccountCreateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<StatusAccountResponseDTOResponseDTO>>;
    statusaccountCreatePost(statusAccountCreateDTO?: StatusAccountCreateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/statusaccount/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, statusAccountCreateDTO, requestOptions);
    }

    statusaccountUpdateIdPut(id: string, statusAccountUpdateDTO?: StatusAccountUpdateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<StatusAccountResponseDTOResponseDTO>;
    statusaccountUpdateIdPut(id: string, statusAccountUpdateDTO?: StatusAccountUpdateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<StatusAccountResponseDTOResponseDTO>>;
    statusaccountUpdateIdPut(id: string, statusAccountUpdateDTO?: StatusAccountUpdateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<StatusAccountResponseDTOResponseDTO>>;
    statusaccountUpdateIdPut(id: string, statusAccountUpdateDTO?: StatusAccountUpdateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/statusaccount/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, statusAccountUpdateDTO, requestOptions);
    }

    statusaccountDeleteIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponseDTO>;
    statusaccountDeleteIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponseDTO>>;
    statusaccountDeleteIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponseDTO>>;
    statusaccountDeleteIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/statusaccount/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
