/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Storage controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";

@Injectable({ providedIn: "root" })
export class StorageService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiStorageHealthGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiStorageHealthGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiStorageHealthGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiStorageHealthGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/storage/health`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiStorageUploadPost(file?: Blob, requestBody?: Record<string, any>, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiStorageUploadPost(file?: Blob, requestBody?: Record<string, any>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiStorageUploadPost(file?: Blob, requestBody?: Record<string, any>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiStorageUploadPost(file?: Blob, requestBody?: Record<string, any>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/storage/upload`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (file !== undefined) {
            formData.append('file', file);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    apiStorageUploadPdfPost(file?: Blob, requestBody?: Record<string, any>, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiStorageUploadPdfPost(file?: Blob, requestBody?: Record<string, any>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiStorageUploadPdfPost(file?: Blob, requestBody?: Record<string, any>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiStorageUploadPdfPost(file?: Blob, requestBody?: Record<string, any>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/storage/upload-pdf`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (file !== undefined) {
            formData.append('file', file);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    apiStorageFileKeyGet(key: string, download?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiStorageFileKeyGet(key: string, download?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiStorageFileKeyGet(key: string, download?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiStorageFileKeyGet(key: string, download?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/storage/file/${key}`;

        let params = new HttpParams();
        if (download != null) {
            params = HttpParamsBuilder.addToHttpParams(params, download, 'download');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiStorageKeyDelete(key: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiStorageKeyDelete(key: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiStorageKeyDelete(key: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiStorageKeyDelete(key: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/storage/${key}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    apiStorageSignedUrlKeyGet(key: string, minutes?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiStorageSignedUrlKeyGet(key: string, minutes?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiStorageSignedUrlKeyGet(key: string, minutes?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiStorageSignedUrlKeyGet(key: string, minutes?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/storage/signed-url/${key}`;

        let params = new HttpParams();
        if (minutes != null) {
            params = HttpParamsBuilder.addToHttpParams(params, minutes, 'minutes');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiStoragePublicUrlKeyGet(key: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiStoragePublicUrlKeyGet(key: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiStoragePublicUrlKeyGet(key: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiStoragePublicUrlKeyGet(key: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/storage/public-url/${key}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
