/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for TypeSlot controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { ObjectResponseDTO, RequestOptions, TypeSlotCreateDTO, TypeSlotResponseDTOListResponseDTO, TypeSlotResponseDTOResponseDTO, TypeSlotUpdateDTO } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";

@Injectable({ providedIn: "root" })
export class TypeSlotService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    typeslotAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<TypeSlotResponseDTOListResponseDTO>;
    typeslotAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TypeSlotResponseDTOListResponseDTO>>;
    typeslotAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TypeSlotResponseDTOListResponseDTO>>;
    typeslotAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/typeslot/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    typeslotIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<TypeSlotResponseDTOResponseDTO>;
    typeslotIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TypeSlotResponseDTOResponseDTO>>;
    typeslotIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TypeSlotResponseDTOResponseDTO>>;
    typeslotIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/typeslot/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    typeslotCreatePost(typeSlotCreateDTO?: TypeSlotCreateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<TypeSlotResponseDTOResponseDTO>;
    typeslotCreatePost(typeSlotCreateDTO?: TypeSlotCreateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TypeSlotResponseDTOResponseDTO>>;
    typeslotCreatePost(typeSlotCreateDTO?: TypeSlotCreateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TypeSlotResponseDTOResponseDTO>>;
    typeslotCreatePost(typeSlotCreateDTO?: TypeSlotCreateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/typeslot/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, typeSlotCreateDTO, requestOptions);
    }

    typeslotUpdateIdPut(id: string, typeSlotUpdateDTO?: TypeSlotUpdateDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<TypeSlotResponseDTOResponseDTO>;
    typeslotUpdateIdPut(id: string, typeSlotUpdateDTO?: TypeSlotUpdateDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TypeSlotResponseDTOResponseDTO>>;
    typeslotUpdateIdPut(id: string, typeSlotUpdateDTO?: TypeSlotUpdateDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TypeSlotResponseDTOResponseDTO>>;
    typeslotUpdateIdPut(id: string, typeSlotUpdateDTO?: TypeSlotUpdateDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/typeslot/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, typeSlotUpdateDTO, requestOptions);
    }

    typeslotDeleteIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponseDTO>;
    typeslotDeleteIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponseDTO>>;
    typeslotDeleteIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponseDTO>>;
    typeslotDeleteIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/typeslot/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
